### ISSUE TITLE
AttributeError: 'str' object has no attribute 'shape'

### ISSUE THREAD

**Issue by NonlinearNimesh** [AmbiTyga/MemSem#1]
Traceback (most recent call last):
  File "train.py", line 10, in <module>
    cls.train(data)
  File "/content/MemSem/model.py", line 85, in train
    model = self.build()
  File "/content/MemSem/model.py", line 59, in build
    dense = Dense(768, activation='relu')(bert_out)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 964, in __call__
    self._maybe_build(inputs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 2398, in _maybe_build
    self.input_spec, inputs, self.name)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/input_spec.py", line 166, in assert_input_compatibility
    if x.shape.ndims is None:
AttributeError: 'str' object has no attribute 'shape'

**Comment by AmbiTyga** [comment]
Try getting data type of `data`, and tell me is that a `str` data type?
> Try running
`type(data)` and `type(data[0])`

**Comment by NonlinearNimesh** [comment]
i read the data.pkl file first:

with open('data.pkl', 'rb') as f:
    data = pickle.load(f)

When i run this **type(data)**

TypeError : Traceback (most recent call last)
<ipython-input-37-c81daa710fff> in <module>()
----> 1 data(type)
TypeError: 'dict' object is not callable
type(data[0])

for **data(type[0])**
TypeError: 'type' object is not subscriptable

**Comment by NonlinearNimesh** [comment]
type(data) is giving me **dict**

and 

type(data[0]) is giving me this below error 
'type' object is not subscriptable

**Comment by amokhvarma** [comment]
Hi @imnimesh , use  transformers==2.11.0 in the requirements and you are good to go !
